# -*- coding: utf-8 -*-
"""usage_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFMgWD0PfajL3uwexva_UJrCvbC0JOsF
"""

# 로컬(VS Code) 실행 환경용 설치 방법 안내(터미널에서 실행)
# python -m pip install langchain-openai langchain faiss-cpu langchain-community langchain-text-splitters unstructured[xlsx]
# pip install langchainhub faiss-cpu langchain-openai langchain langgraph typing typing_extensions langchain_core langchain-community
# pip install -U langchain-openai langchain-community langchain-text-splitters
# pip install -q pillow unstructured msoffcrypto-tool

# -*- coding: utf-8 -*-

import os
import glob
import warnings
from pathlib import Path
from typing import Sequence

warnings.filterwarnings("ignore", category=DeprecationWarning)

# =========================
# 1. 프로젝트 경로 설정
# =========================
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
FAISS_DIR = BASE_DIR / "faiss_index"

# =========================
# 2. API KEY 로드
# =========================
def load_api_keys(filepath: Path):
    if not filepath.exists():
        raise FileNotFoundError(f"API 키 파일이 없습니다: {filepath}")
    with filepath.open("r", encoding="utf-8") as f:
        for line in f:
            if "=" in line:
                k, v = line.strip().split("=", 1)
                os.environ[k.strip()] = v.strip()

load_api_keys(BASE_DIR / "usage_api.txt")

# =========================
# 3. LangChain imports
# =========================
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import UnstructuredExcelLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough

# =========================
# 4. 데이터 로딩
# =========================
excel_path = DATA_DIR / "api정의서.xlsx"

if not excel_path.exists():
    raise FileNotFoundError("api정의서.xlsx 파일이 없습니다.")

excel_loader = UnstructuredExcelLoader(str(excel_path))
excel_docs = excel_loader.load()

# 이미지 파일은 문서 설명 참고용 → 텍스트 RAG에는 제외
print(f"엑셀 문서 수: {len(excel_docs)}")

# =========================
# 5. 문서 분할
# =========================
splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

split_docs = splitter.split_documents(excel_docs)

# =========================
# 6. 벡터 DB 생성
# =========================
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

vectorstore = FAISS.from_documents(split_docs, embeddings)
vectorstore.save_local(str(FAISS_DIR))

vectorstore = FAISS.load_local(
    str(FAISS_DIR),
    embeddings,
    allow_dangerous_deserialization=True
)

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 3}
)

# =========================
# 7. 프롬프트 & LLM
# =========================
prompt = ChatPromptTemplate.from_template("""
당신은 대한민국의 공무원이자
"나라장터 기반 조달·입찰 인텔리전스 플랫폼" 사이트 운영자이다.

문서를 참고하여 웹사이트의 기능을 설명하라.

- API 정의서 자체를 설명하지 말 것
- 소형·중형 건설사가 이해할 수 있게 설명
- 사용 방법 중심으로 서술

[문서]
{context}

[질문]
{question}
""")

llm = ChatOpenAI(
    model="gpt-5-nano",
    temperature=0
)

qa_chain = (
    {
        "context": retriever,
        "question": RunnablePassthrough()
    }
    | prompt
    | llm
)

# =========================
# 8. 실행 테스트
# =========================
# content 만 보여주기
# response = qa_chain.invoke("로그인은 어디에서 할 수 있나요?")
# print(response.content)
response2 = qa_chain.invoke("공고찾기 페이지는 어떻게 사용하는 것인지 설명해줘.")
print(response2.content)

# 전체 출력 내용
# response3 = qa_chain.invoke("로그인은 어디에서 할 수 있나요?")
# print(response3)
response4 = qa_chain.invoke("공고찾기 페이지는 어떻게 사용하는 것인지 설명해줘.")
print(response4)

