# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_d6rkQSe4r4TJ_CFCWxdQHa-NBGoMQY
"""

import requests
import pandas as pd

SERVICE_KEY = "4244f2d0585c4637ce8b73310c8d6d4e70fb663f8c0c5d5ab31d6c43271e2d8a"
numOfRows=5 #int형태, 몇건 불러올지
inqryBgnDt="202501010000" #시작날짜
inqryEndDt="202501312358" #끝날짜
filename="저장할csv파일이름"
# ----------------------------------
# 1. 공사 기초금액 + 예가범위
# ----------------------------------
url_bssis = "https://apis.data.go.kr/1230000/ad/BidPublicInfoService/getBidPblancListInfoCnstwkBsisAmount"

params_bssis = {
    "serviceKey": SERVICE_KEY,
    "pageNo": 1,
    "numOfRows": numOfRows,
    "inqryDiv": 1,
    "inqryBgnDt": inqryBgnDt,
    "inqryEndDt": inqryEndDt,
    "type": "json",
}

res = requests.get(url_bssis, params=params_bssis).json()
items = res.get("response", {}).get("body", {}).get("items", [])

if isinstance(items, dict):
    items = items.get("item", [])

df_bssis = pd.DataFrame(items)

df_bssis = df_bssis[[
    "bidNtceNo",
    "bidNtceNm",
    "bssamt",
    "rsrvtnPrceRngBgnRate",
    "rsrvtnPrceRngEndRate"
]]

# 예가범위: 시작/종료 절대값 중 큰 값
df_bssis["예가범위"] = df_bssis[
    ["rsrvtnPrceRngBgnRate", "rsrvtnPrceRngEndRate"]
].apply(
    lambda x: max(
        abs(pd.to_numeric(x.iloc[0], errors="coerce")),
        abs(pd.to_numeric(x.iloc[1], errors="coerce"))
    ),
    axis=1
)

df_bssis = df_bssis.rename(columns={
    "bssamt": "기초금액"
})

df_bssis = df_bssis[["bidNtceNo", "bidNtceNm", "기초금액", "예가범위"]]

# ----------------------------------
# 2. 예정가격 (개찰결과 예비가격 상세)
# ----------------------------------
url_openg = "https://apis.data.go.kr/1230000/as/ScsbidInfoService/getOpengResultListInfoCnstwkPreparPcDetail"

openg_rows = []

for bid_no in df_bssis["bidNtceNo"].dropna().unique():
    params_openg = {
        "serviceKey": SERVICE_KEY,
        "pageNo": 1,
        "numOfRows": 1,
        "inqryDiv": 2,        # 공고번호 기준
        "bidNtceNo": bid_no,
        "type": "json",
    }

    try:
        res = requests.get(url_openg, params=params_openg, timeout=10).json()
        items = res.get("response", {}).get("body", {}).get("items", [])

        if isinstance(items, dict):
            items = items.get("item", [])

        for item in items:
            openg_rows.append({
                "bidNtceNo": item.get("bidNtceNo"),
                "예정가격": item.get("plnprc")
            })

    except Exception as e:
        # 오류 나도 그냥 넘어감 (결측 유지)
        continue

df_openg = pd.DataFrame(openg_rows)

# ----------------------------------
# 3. 낙찰하한율 (공고 상세 검색)
# ----------------------------------
url_rate = "https://apis.data.go.kr/1230000/ad/BidPublicInfoService/getBidPblancListInfoCnstwkPPSSrch"

params_rate = {
    "serviceKey": SERVICE_KEY,
    "pageNo": 1,
    "numOfRows": numOfRows,
    "inqryDiv": 1,
    "inqryBgnDt": inqryBgnDt,
    "inqryEndDt": inqryEndDt,
    "type": "json",
}

res = requests.get(url_rate, params=params_rate).json()
items = res.get("response", {}).get("body", {}).get("items", [])

if isinstance(items, dict):
    items = items.get("item", [])

df_rate = pd.DataFrame(items)

df_rate = df_rate[[
    "bidNtceNo",
    "sucsfbidLwltRate"
]]

df_rate = df_rate.rename(columns={
    "sucsfbidLwltRate": "낙찰하한율"
})


# ----------------------------------
# 4. DataFrame 병합 (결측치 그대로 유지)
# ----------------------------------
df_all = df_bssis.merge(df_openg, on="bidNtceNo", how="left")
df_all = df_all.merge(df_rate, on="bidNtceNo", how="left")

# # 숫자형 변환 (실패 시 NaN 유지)
# for col in ["기초금액", "예정가격", "예가범위", "낙찰하한율"]:
#     if col in df_all.columns:
#         df_all[col] = pd.to_numeric(df_all[col], errors="coerce")
df = (
    df_all.groupby("bidNtceNo", as_index=False)
      .agg({
          "bidNtceNm": "first",
          "기초금액": "first",
          "예가범위": "first",
          "예정가격": "first",
          "낙찰하한율": "first"
      })
)


# ----------------------------------
# 5. 낙찰가 (최종 낙찰 목록)
# ----------------------------------
url_scsbid = "https://apis.data.go.kr/1230000/as/ScsbidInfoService/getScsbidListSttusCnstwkPPSSrch"

rows = []

for bid_no in df["bidNtceNo"].dropna().unique():
    params = {
        "serviceKey": SERVICE_KEY,
        "inqryDiv": 3,        # 공고번호 기준
        "bidNtceNo": bid_no,
        "pageNo": 1,
        "numOfRows": numOfRows,
        "type": "json",
    }

    res = requests.get(url_scsbid, params=params).json()
    items = res.get("response", {}).get("body", {}).get("items", [])

    if isinstance(items, dict):
        items = items.get("item", [])

    for item in items:
        rows.append({
            "bidNtceNo": bid_no,
            "낙찰가": item.get("sucsfbidAmt"),
            #"낙찰률": item.get("sucsfbidRate"),
        })

df_scsbid = pd.DataFrame(rows)
df = df.merge(df_scsbid, on="bidNtceNo", how="left")
df.to_csv(filename, index=False, encoding="utf-8-sig")